# Generated by Django 5.0.1 on 2024-01-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_addiction_customuser_challenges_done_and_more"),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addiction",
            name="educational",
            field=models.ManyToManyField(blank=True, to="challenges.educational"),
        ),
        migrations.AddField(
            model_name="addiction",
            name="question_sets",
            field=models.ManyToManyField(blank=True, to="challenges.questionset"),
        ),
        migrations.AddField(
            model_name="addiction",
            name="socratic_dialogue_questions",
            field=models.ManyToManyField(
                blank=True, to="challenges.socraticdialoguequestions"
            ),
        ),
        migrations.AddField(
            model_name="addiction",
            name="time_events",
            field=models.ManyToManyField(blank=True, to="challenges.timeevent"),
        ),
    ]
