
name: CI
on: [push, pull_request]
env:
  POSTGRES_HOST: localhost
  POSTGRES_DB: github_actions
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run tests
        run: pytest -n 2
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run black
        run: black --check --verbose bitehack2024/
      - name: Run flake
        run: flake8 bitehack2024/
      - name: Check imports with isort
        run: isort --check bitehack2024/
      - name: Run mypy
        run: mypy --config-file mypy.ini bitehack2024/
